import os

# Image generation chat
IMAGE_GENERATION_CHAT_HOST = os.getenv('IMAGE_GENERATION_CHAT_HOST')
IMAGE_GENERATION_CHAT_QUEUE = os.getenv('IMAGE_GENERATION_CHAT_REQUEST_QUEUE')
IMAGE_GENERATION_CHAT_RESPONSE_QUEUE = os.getenv('IMAGE_GENERATION_CHAT_RESPONSE_QUEUE')
IMAGE_GENERATION_CHAT_PORT = os.getenv('IMAGE_GENERATION_CHAT_PORT')
IMAGE_GENERATION_CHAT_USERNAME = os.getenv('IMAGE_GENERATION_CHAT_USERNAME')
IMAGE_GENERATION_CHAT_PASSWORD = os.getenv('IMAGE_GENERATION_CHAT_PASSWORD')

# Vote AI
VOTE_AI_HOST = os.getenv('VOTE_AI_HOST')
VOTE_AI_REQUEST_QUEUE = os.getenv('VOTE_AI_REQUEST_QUEUE')
VOTE_AI_RESPONSE_QUEUE = os.getenv('VOTE_AI_RESPONSE_QUEUE')
VOTE_AI_PORT = os.getenv('VOTE_AI_PORT')
VOTE_AI_USERNAME = os.getenv('VOTE_AI_USERNAME')
VOTE_AI_PASSWORD = os.getenv('VOTE_AI_PASSWORD')
