import os


# RabbitMQ
RABBITMQ_HOST = os.getenv('RABBITMQ_HOST')
REQUEST_QUEUE = os.getenv('REQUEST_QUEUE')
RESPONSE_QUEUE = os.getenv('RESPONSE_QUEUE')
RABBITMQ_PORT = os.getenv('RABBITMQ_PORT')
RABBITMQ_USERNAME = os.getenv('RABBITMQ_USERNAME')
RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD')
